// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  /*
  tutorialSidebar: [
    'intro',
    {
      type: 'doc',
      label: 'Books',
    },
  ],
   */
};

module.exports = sidebars;
